name: advance_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 2.0.2
homepage: https://github.com/adampermana/pdf_viewer
repository: https://github.com/adampermana/pdf_viewer

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  numberpicker: ^2.1.2
  path_provider: ^2.1.4

dev_dependencies:
  lint: ^2.3.0

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
